#ifndef MMODERN_RESTORE_REPLAY_PROBE_H
#define MMODERN_RESTORE_REPLAY_PROBE_H
// Executable-only GNU linker probes for the pinned Windows/UCRT64 test build.
// No callbacks or counters are installed in production gameplay owners.
#define XEEN_REPLAY_CONSTRUCT "_ZN7mmodern10XeenCombatC1ERNS_9XeenWorldERNS_14XeenPartyStateERNS_10XeenCameraERNS_18XeenCombatBoundaryERKSt6vectorIhSaIhEERKNS_19XeenGameplayContextERKS9_INS_17XeenMonsterRecordESaISH_EERKNS_13XeenEventFileENS_16XeenCombatRandomE"
#define XEEN_REPLAY_SERVICE "_ZN7mmodern10XeenCombat7serviceERKNS0_6TicketE"
#define XEEN_REPLAY_INITIALIZE "_ZN7mmodern17XeenActorApproach10initializeERNS_9XeenWorldERNS_14XeenPartyStateERNS_10XeenCameraERNS_18XeenEncounterStateERKSt6vectorINS_17XeenMonsterRecordESaISA_EERKNS_19XeenGameplayContextERKNS_13XeenEventFileE"
#define XEEN_REPLAY_MOVE "_ZN7mmodern17XeenActorApproach4moveERKSt6vectorINS_9XeenActorESaIS2_EERKNS_10XeenCameraERKSt8functionIFNS_18XeenMonsterTerrainERKS2_iiEEb"
#define XEEN_REPLAY_TRANSFER "_ZN7mmodern16xeenTransferItemERNS_14XeenPartyStateEyyNS_21XeenInventoryCategoryEy"
#define XEEN_REPLAY_EQUIPMENT "_ZN7mmodern16xeenSetEquipmentERNS_14XeenPartyStateEyNS_21XeenInventoryCategoryEyNS_22XeenEquipmentOperationE"
#define XEEN_REPLAY_EVENT "_ZNK7mmodern20XeenEventInterpreter7executeERKNS_10XeenCameraERNS_14XeenPartyStateERKNS_13XeenGameFlagsERNS_9XeenWorldERKSt8functionIFNS_15XeenEventScriptENS_15XeenMapIdentityEEE"
#define XEEN_REPLAY_EVENT_BEGIN "_ZNK7mmodern20XeenEventInterpreter5beginERKNS_10XeenCameraERNS_14XeenPartyStateERKNS_13XeenGameFlagsERNS_9XeenWorldERKSt8functionIFNS_15XeenEventScriptENS_15XeenMapIdentityEEERKSB_IFNS_17XeenEventTextFileESD_EEh"
namespace replay_test {
extern unsigned depth, unexpected, constructions, services, preparations;
struct Scope { Scope() { ++depth; } ~Scope() { --depth; } };
}
#endif
